name: pomodoro_timer
description: A pomodoro timer app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.2
  stack_trace: ^1.11.0
  logging: ^1.1.1
  json_annotation: 4.8.0
  json_serializable: 6.6.1
  provider: ^6.0.5
  shared_preferences: 2.0.17
  dartx: 1.1.0
  mobx: 2.2.0
  flutter_mobx: ^2.0.6+5
  permission_handler: ^10.2.0
  equatable: 2.0.5
  analyzer: 5.12.0
  flutter_svg: 2.0.4
  drift: 2.8.0
  sqlite3_flutter_libs: 0.5.14
  path_provider: 2.0.15
  path: 1.8.3
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  lint: 2.1.1
  drift_dev: 2.8.1
  build_runner: 2.4.4
  mobx_codegen: 2.3.0

# The following section is specific to Flutter.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/icons/
    - assets/images/
    - assets/onboarding/