name: base_template_app
description: A base template for flutter apps

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  stack_trace: ^1.11.0
  logging: ^1.1.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dartx: ^1.1.0
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  analyzer: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^2.0.1
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

